var hr_Constants = {
		CASE_DRAFT						: 1,
		CASE_CLOSED_COMPLETE 			: 3,
		CASE_CLOSED_INCOMPLETE 			: 4,
		CASE_RESOLVED					: 6,
		CASE_CANCELLED 					: 7,
		CASE_QUALIFIED 					: 10,
		CASE_AWAITING_APPROVAL 			: 11,
		CASE_APPROVED 					: 13,
		CASE_AWAITING_QUALIFICATION 	: 15,
		CASE_ASSIGNED 					: 16,
		CASE_WORK_IN_PROGRESS 			: 18,
		CASE_AWAITING_USER_ACCEPTANCE	: 20,
		TASK_DRAFT 						: 1,
		TASK_CLOSED_COMPLETE 			: 3,
		TASK_CLOSED_INCOMPLETE 			: 4,
		TASK_CANCELLED 					: 7,
		TASK_PENDING_DISPATCH 			: 10,
		TASK_ASSIGNED 					: 16,
		TASK_ACCEPTED 					: 17,
		TASK_WORK_IN_PROGRESS 			: 18,
	
		ROLLUP_WORK_NOTES               : "sn_hr_core.rollup_work_notes",
		MANDATORY_WORK_NOTES            : "sn_hr_core.mandatory_work_notes",
		MANAGED_DOCUMENTS               : "sn_hr_core.managed_documents"
	};